Repository shipwright-io/cli, pull requests merged in 2021-09, with the labels that each got.

#39 Start buildrun follow logs test
  pkg/shp/cmd/build/run.go
  pkg/shp/cmd/build/run_test.go
Labels: kind/cleanup, approved, lgtm, release-note-none

#40 Bootstrapping End-to-End Tests
  .github/workflows/e2e.yaml
  .github/workflows/unit.yaml
  Makefile
  README.md
  docs/testing.md
  hack/install-shipwright.sh
  hack/install-tekton.sh
  hack/verify-kind.sh
  test/e2e/e2e.bats
  test/e2e/helpers.sh
Labels: kind/design, approved, lgtm, release-note-none

#41 more multi thread coordination need to avoid panics in TestStartBuildRunFollowLog
  pkg/shp/cmd/build/run_test.go
Labels: kind/bug, approved, lgtm, release-note-none

#45 Pass name to shp for create build and create buildrun
  pkg/shp/cmd/build/create.go
  pkg/shp/cmd/buildrun/create.go
  test/e2e/e2e.bats
  test/e2e/helpers.sh
Labels: kind/bug, approved, lgtm, release-note

#46 add container registry to e2e
  .github/workflows/e2e.yaml
  test/data/registry.yaml
Labels: kind/cleanup, approved, lgtm, release-note-none

#49 more RunCommand initialization verification for TestStartBuildRunFollowLogs
  pkg/shp/cmd/build/run_test.go
Labels: kind/bug, approved, lgtm, release-note-none
