Repository shipwright-io/cli, pull requests merged in 2021-07, with the labels that each got.

#28 Fixing Pointer-to-String Flags and Improve Testing
  pkg/shp/flags/build.go
  pkg/shp/flags/build_test.go
  pkg/shp/flags/buildrun.go
  pkg/shp/flags/buildrun_test.go
  pkg/shp/flags/doc.go
  pkg/shp/flags/flags.go
  pkg/shp/flags/strategy_kind_value.go
  pkg/shp/flags/strategy_kind_value_test.go
  pkg/shp/flags/string_pointer_value_test.go
Labels: approved, kind/bug, lgtm, release-note

#29 Updating Old References
  README.md
Labels: approved, lgtm, release-note-none

#33 Update `OWNERS` file
  OWNERS
Labels: approved, kind/cleanup, lgtm, release-note-none

#32 Fix command line parsing of build command
  go.mod
  go.sum
  pkg/shp/flags/build.go
  pkg/shp/flags/build_test.go
  pkg/shp/flags/flags.go
  vendor/k8s.io/utils/pointer/OWNERS
  vendor/k8s.io/utils/pointer/README.md
  vendor/k8s.io/utils/pointer/pointer.go
  vendor/modules.txt
Labels: approved, kind/bug, lgtm, release-note

#30 Go-Report-Card Fixes
  pkg/shp/cmd/build/doc.go
  pkg/shp/cmd/buildrun/buildrun.go
  pkg/shp/cmd/buildrun/doc.go
  pkg/shp/flags/doc.go
  pkg/shp/flags/flags.go
  pkg/shp/params/params.go
  pkg/shp/reactor/pod_watcher.go
  pkg/shp/resource/doc.go
  pkg/shp/resource/resource.go
  pkg/shp/util/crud.go
  pkg/shp/util/doc.go
Labels: approved, kind/cleanup, lgtm, release-note-none

#31 Add generic Kubectl binary download script for all Linux distributions
  hack/install-kubectl.sh
Labels: approved, lgtm, release-note-none

#22 add buildrun cancel
  go.mod
  go.sum
  pkg/shp/cmd/build/run.go
  pkg/shp/cmd/buildrun/buildrun.go
  pkg/shp/cmd/buildrun/cancel.go
  pkg/shp/params/params.go
  pkg/shp/reactor/pod_watcher.go
  pkg/shp/resource/resource.go
  pkg/shp/tail/tail.go
  pkg/shp/util/crud.go
  vendor/github.com/shipwright-io/build/pkg/apis/build/v1alpha1/build_types.go
  vendor/github.com/shipwright-io/build/pkg/apis/build/v1alpha1/buildrun_types.go
  vendor/github.com/shipwright-io/build/pkg/apis/build/v1alpha1/buildstrategy.go
  vendor/github.com/shipwright-io/build/pkg/apis/build/v1alpha1/buildstrategy_types.go
  vendor/github.com/shipwright-io/build/pkg/apis/build/v1alpha1/clusterbuildstrategy_types.go
  vendor/github.com/shipwright-io/build/pkg/apis/build/v1alpha1/parameter.go
  vendor/github.com/shipwright-io/build/pkg/apis/build/v1alpha1/zz_generated.deepcopy.go
  vendor/github.com/shipwright-io/build/pkg/client/clientset/versioned/clientset.go
  vendor/github.com/shipwright-io/build/pkg/client/clientset/versioned/doc.go
  vendor/github.com/shipwright-io/build/pkg/client/clientset/versioned/scheme/doc.go
  vendor/github.com/shipwright-io/build/pkg/client/clientset/versioned/scheme/register.go
  vendor/github.com/shipwright-io/build/pkg/client/clientset/versioned/typed/build/v1alpha1/build.go
  vendor/github.com/shipwright-io/build/pkg/client/clientset/versioned/typed/build/v1alpha1/build_client.go
  vendor/github.com/shipwright-io/build/pkg/client/clientset/versioned/typed/build/v1alpha1/buildrun.go
  vendor/github.com/shipwright-io/build/pkg/client/clientset/versioned/typed/build/v1alpha1/buildstrategy.go
  vendor/github.com/shipwright-io/build/pkg/client/clientset/versioned/typed/build/v1alpha1/clusterbuildstrategy.go
  vendor/github.com/shipwright-io/build/pkg/client/clientset/versioned/typed/build/v1alpha1/doc.go
  vendor/github.com/shipwright-io/build/pkg/client/clientset/versioned/typed/build/v1alpha1/generated_expansion.go
  vendor/modules.txt
Labels: approved, kind/feature, lgtm, release-note

#36 remove use of dynamic client; add tests with more reliable static clients
  go.mod
  pkg/shp/cmd/build/create.go
  pkg/shp/cmd/build/delete.go
  pkg/shp/cmd/build/list.go
  pkg/shp/cmd/build/run.go
  pkg/shp/cmd/buildrun/cancel.go
  pkg/shp/cmd/buildrun/cancel_test.go
  pkg/shp/cmd/buildrun/create.go
  pkg/shp/cmd/buildrun/delete.go
  pkg/shp/cmd/buildrun/list.go
  pkg/shp/cmd/buildrun/logs.go
  pkg/shp/cmd/buildrun/logs_test.go
  pkg/shp/params/params.go
  pkg/shp/params/params_test.go
  pkg/shp/resource/doc.go
  pkg/shp/resource/factory.go
  pkg/shp/resource/resource.go
  pkg/shp/resource/resource_test.go
  pkg/shp/util/crud.go
  pkg/shp/util/crud_test.go
  vendor/github.com/shipwright-io/build/pkg/client/clientset/versioned/fake/clientset_generated.go
  vendor/github.com/shipwright-io/build/pkg/client/clientset/versioned/fake/doc.go
  vendor/github.com/shipwright-io/build/pkg/client/clientset/versioned/fake/register.go
  vendor/github.com/shipwright-io/build/pkg/client/clientset/versioned/typed/build/v1alpha1/fake/doc.go
  vendor/github.com/shipwright-io/build/pkg/client/clientset/versioned/typed/build/v1alpha1/fake/fake_build.go
  vendor/github.com/shipwright-io/build/pkg/client/clientset/versioned/typed/build/v1alpha1/fake/fake_build_client.go
  vendor/github.com/shipwright-io/build/pkg/client/clientset/versioned/typed/build/v1alpha1/fake/fake_buildrun.go
  vendor/github.com/shipwright-io/build/pkg/client/clientset/versioned/typed/build/v1alpha1/fake/fake_buildstrategy.go
  vendor/github.com/shipwright-io/build/pkg/client/clientset/versioned/typed/build/v1alpha1/fake/fake_clusterbuildstrategy.go
  vendor/modules.txt
Labels: approved, kind/cleanup, lgtm, release-note
