Repository shipwright-io/cli, pull requests merged in 2021-12, with the labels that each got.

#62 pull in draft release notes script from build repo
  .github/draft_release_notes.sh
Labels: kind/cleanup, approved, lgtm, release-note-none

#79 Use golangci-lint
  .github/workflows/verify.yaml
  .golangci.yml
  pkg/shp/flags/map_value_test.go
Labels: kind/cleanup, ok-to-test, approved, lgtm, release-note-none

#84 Increase golangci-lint timeout
  .github/workflows/verify.yaml
Labels: kind/failing-test, approved, lgtm, release-note-none

#83 adjust shp build run -F e2e so that buildpacks build actually fully completes successfully
  test/e2e/run-follow.bats
Labels: kind/cleanup, approved, lgtm, release-note-none

#76 Adds support for img labels and anno. in buildrun create cmd
  pkg/shp/flags/buildrun.go
  pkg/shp/flags/buildrun_test.go
  pkg/shp/flags/flags.go
  test/e2e/output-image-labels-annotations.bats
Labels: approved, lgtm, release-note

#81 add -F / --follow options to shp buildrun logs
  pkg/shp/cmd/build/run.go
  pkg/shp/cmd/build/run_test.go
  pkg/shp/cmd/buildrun/logs.go
  pkg/shp/cmd/buildrun/logs_test.go
  pkg/shp/cmd/follower/follow.go
  pkg/shp/params/params.go
  test/e2e/log-follow--follow.bats
  test/e2e/log-follow-F.bats
Labels: kind/feature, approved, lgtm, release-note

#85 Generate cleaner release notes
  .github/draft_release_notes.sh
  .github/workflows/release.yml
Labels: kind/cleanup, approved, lgtm, release-note-none
