Repository shipwright-io/cli, pull requests merged in 2022-04, with the labels that each got.

#107 Optional Source URL
  pkg/shp/cmd/build/create.go
Labels: approved, lgtm, release-note

#108 Hide Kubernetes and Logging flags
  cmd/shp/main.go
  docs/shp.md
  docs/shp_build.md
  docs/shp_build_create.md
  docs/shp_build_delete.md
  docs/shp_build_list.md
  docs/shp_build_run.md
  docs/shp_build_upload.md
  docs/shp_buildrun.md
  docs/shp_buildrun_cancel.md
  docs/shp_buildrun_create.md
  docs/shp_buildrun_delete.md
  docs/shp_buildrun_list.md
  docs/shp_buildrun_logs.md
  docs/shp_version.md
  pkg/shp/params/params.go
  test/e2e/e2e.bats
Labels: approved, lgtm, release-note-none

#111 Add retention flags
  docs/shp_build_create.md
  docs/shp_build_run.md
  docs/shp_build_upload.md
  docs/shp_buildrun_create.md
  pkg/shp/cmd/build/list.go
  pkg/shp/flags/build.go
  pkg/shp/flags/build_test.go
  pkg/shp/flags/buildrun.go
  pkg/shp/flags/buildrun_test.go
  pkg/shp/flags/flags.go
Labels: kind/feature, approved, lgtm, release-note

#112 fix flakes in log following related unit tests
  pkg/shp/cmd/build/run.go
  pkg/shp/cmd/build/run_test.go
  pkg/shp/cmd/buildrun/cancel_test.go
  pkg/shp/cmd/buildrun/logs_test.go
  pkg/shp/cmd/follower/follow.go
  pkg/shp/params/params.go
  pkg/shp/reactor/pod_watcher.go
  pkg/shp/reactor/pod_watcher_test.go
Labels: kind/cleanup, approved, lgtm, release-note-none
