Repository shipwright-io/cli, pull requests merged in 2022-01, with the labels that each got.

#92 Use golangci-lint in Makefile
  .golangci.yml
  Makefile
  pkg/shp/cmd/build/upload.go
  test/mock/fake_remote_executor.go
Labels: kind/cleanup, approved, lgtm, release-note-none

#93 update pod watcher to handle all events occurring before the pod watcher is started
  pkg/shp/cmd/build/run_test.go
  pkg/shp/cmd/buildrun/logs_test.go
  pkg/shp/cmd/follower/follow.go
  pkg/shp/reactor/pod_watcher.go
  pkg/shp/reactor/pod_watcher_test.go
Labels: kind/cleanup, approved, lgtm, release-note

#91 Local Source Upload Doc.
  docs/local_source_upload.md
Labels: kind/documentation, approved, lgtm, release-note-none

#95 Shipwright Release v0.8.0
  Makefile
  go.mod
  go.sum
  hack/install-shipwright.sh
  vendor/github.com/shipwright-io/build/pkg/apis/build/v1alpha1/build_types.go
  vendor/github.com/shipwright-io/build/pkg/apis/build/v1alpha1/buildstrategy.go
  vendor/github.com/shipwright-io/build/pkg/apis/build/v1alpha1/parameter.go
  vendor/github.com/shipwright-io/build/pkg/apis/build/v1alpha1/zz_generated.deepcopy.go
  vendor/modules.txt
Labels: approved, area/dependency, lgtm, release-note-none

#96 fix copy/paste error when grabbing script from build repo
  .github/draft_release_notes.sh
Labels: kind/cleanup, approved, lgtm, release-note-none
