Repository shipwright-io/cli, pull requests merged in 2023-08, with the labels that each got.

#192 Add issues workflow and remove pull request template
  .github/pull_request_template.md
  .github/workflows/issues.yml
Labels: kind/cleanup, lgtm, release-note-none

#193 Update Approvers and Reviewers
  OWNERS
Labels: size/XS, kind/documentation, approved, lgtm, release-note-none

#196 Update shipwright-io/setup configuration to build from main branch
  .github/workflows/e2e.yaml
Labels: size/XS, kind/failing-test, release-note-none

#194 Update installation instructions
  README.md
Labels: size/XS, kind/cleanup, approved, lgtm, release-note-none
